In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import statsmodels.formula.api as sm


# Aplicando a Regressão Limples

In [45]:
dados = pd.read_csv('Healthcare-Diabetes.csv')

In [5]:
dados.head()

Id  Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0   1            6      148             72             35        0  33.6   
1   2            1       85             66             29        0  26.6   
2   3            8      183             64              0        0  23.3   
3   4            1       89             66             23       94  28.1   
4   5            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [7]:
dados = dados.drop(['Id'], axis = 1)

In [8]:
dados.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [28]:
X = dados.loc[:, 'BMI'].values
y = dados.loc[:, 'SkinThickness'].values


In [29]:
correlacao = np.corrcoef(X,y)
correlacao

array([[1.        , 0.39349429],
       [0.39349429, 1.        ]])

In [76]:
X = X.reshape(-1,1)
X

array([[33.6],
       [26.6],
       [23.3],
       ...,
       [31.2],
       [67.1],
       [30.1]])

In [77]:
modelo = LinearRegression()
modelo.fit(X,y)

LinearRegression()

In [32]:
#Interceptação
modelo.intercept_

-4.322250270524037

In [33]:
#score R^2
modelo.score(X,y)

0.15483776002487504

In [34]:
#gerando a previsões
previsoes = modelo.predict(X)
previsoes

array([21.96887494, 16.49155719, 13.90939311, ..., 20.09093743,
       48.18175276, 19.23021607])

In [35]:
# Criando o modelo utilizando a biblioteca statsmodel

modelo_ajustado = sm.ols(formula = 'BMI ~ SkinThickness', data= dados)
modelo_treinado = modelo_ajustado.fit()
modelo_treinado.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    BMI   R-squared:                       0.155
Model:                            OLS   Adj. R-squared:                  0.155
Method:                 Least Squares   F-statistic:                     506.7
Date:                Fri, 01 Sep 2023   Prob (F-statistic):          3.49e-103
Time:                        09:42:38   Log-Likelihood:                -9476.4
No. Observations:                2768   AIC:                         1.896e+04
Df Residuals:                    2766   BIC:                         1.897e+04
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept        28.0166      0.231    121.203      0.000      27.563      28.470
SkinThickness     0.1979      0.009     22.511      0.000       0.181       0.215
==============================================================================
Omnibus:                      314.498   Durbin-Watson:                   1.871
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2865.204
Skew:                           0.099   Prob(JB):                         0.00
Kurtosis:                       7.980   Cond. No.                         43.1
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [36]:
modelo.predict([[26.16]])

array([16.14726865])

# Aplicando a Regressão Multipla

In [64]:
X1 = dados.drop(['Id','SkinThickness'], axis = 1).values

In [65]:
y1 = dados.loc[:,'SkinThickness'].values

In [66]:
modelo2 =LinearRegression()
modelo2.fit(X1,y1)

LinearRegression()

In [67]:
modelo2.score(X1,y1)

0.33287456498150036

In [71]:
novo = np.array([0,85,60,0,26,0.423,24,0])
novo = novo.reshape(1,-1)


In [72]:
novo

array([[ 0.   , 85.   , 60.   ,  0.   , 26.   ,  0.423, 24.   ,  0.   ]])

In [73]:
modelo2.predict(novo)

array([15.09057577])